export const TOKENS = {
  UserRepo: Symbol('UserRepository'),
  RefreshTokenRepo: Symbol('RefreshTokenRepository'),
  StoreUserRepo: Symbol('StoreUserRepository'),
  StoreUserRefreshTokenRepo: Symbol('StoreUserRefreshTokenRepository'),
  ProductRepo: Symbol('ProductRepository'),
  VariantRepo: Symbol('VariantRepository'),
  CategoryRepo: Symbol('CategoryRepository'),
  InventoryRepo: Symbol('InventoryRepository'),
  StoreRepo: Symbol('StoreRepository'),
  AdminStoreRepo: Symbol('AdminStoreRepository'),
  CartRepo: Symbol('CartRepository'),
  AddressRepo: Symbol('AddressRepository'),
  SupplierRepo: Symbol('SupplierRepository'),
  StockOrderRepo: Symbol('StockOrderRepository'),
};
