export const TOKENS = {
  UserRepo: Symbol('UserRepository'),
  RefreshTokenRepo: Symbol('RefreshTokenRepository'),
  StoreUserRepo: Symbol('StoreUserRepository'),
  StoreUserRefreshTokenRepo: Symbol('StoreUserRefreshTokenRepository'),
  ProductRepo: Symbol('ProductRepository'),
  VariantRepo: Symbol('VariantRepository'),
  CategoryRepo: Symbol('CategoryRepository'),
  InventoryRepo: Symbol('InventoryRepository'),
  StoreRepo: Symbol('StoreRepository'),
  AdminStoreRepo: Symbol('AdminStoreRepository'),
  CartRepo: Symbol('CartRepository'),
  AddressRepo: Symbol('AddressRepository'),
  SupplierRepo: Symbol('SupplierRepository'),
  StockOrderRepo: Symbol('StockOrderRepository'),
  StockReceiptRepo: Symbol('StockReceiptRepository'),
  LeadRepo: Symbol('LeadRepository'),
  OrderRepo: Symbol('OrderRepository'),
  SuperAdminRepo: Symbol('SuperAdminRepository'),
  SuperAdminRefreshTokenRepo: Symbol('SuperAdminRefreshTokenRepository'),
  TenantRepo: Symbol('TenantRepository'),
  PlanPriceRepo: Symbol('PlanPriceRepository'),
  SubscriptionRepo: Symbol('SubscriptionRepository'),
  InvoiceRepo: Symbol('InvoiceRepository'),
};
